// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLgN4YdoyhmndNPq4q81Tfq3Sog28q_8M',
    appId: '1:1033058559470:web:86da175092b1c98ecd1aff',
    messagingSenderId: '1033058559470',
    projectId: 'consiergego',
    authDomain: 'consiergego.firebaseapp.com',
    storageBucket: 'consiergego.firebasestorage.app',
    measurementId: 'G-PQX1WP1KC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmRFdmWv7tf_Xr4ZhWJvsa5bCB7oc0OYk',
    appId: '1:1033058559470:android:154681fb3c876295cd1aff',
    messagingSenderId: '1033058559470',
    projectId: 'consiergego',
    storageBucket: 'consiergego.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqn69lXLZ3UKJUnC_TBDL00mufMbWFv2E',
    appId: '1:1033058559470:ios:0b1a1614a0e15fa1cd1aff',
    messagingSenderId: '1033058559470',
    projectId: 'consiergego',
    storageBucket: 'consiergego.firebasestorage.app',
    iosBundleId: 'kg.conciergego.conciergego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqn69lXLZ3UKJUnC_TBDL00mufMbWFv2E',
    appId: '1:1033058559470:ios:0b1a1614a0e15fa1cd1aff',
    messagingSenderId: '1033058559470',
    projectId: 'consiergego',
    storageBucket: 'consiergego.firebasestorage.app',
    iosBundleId: 'kg.conciergego.conciergego',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLgN4YdoyhmndNPq4q81Tfq3Sog28q_8M',
    appId: '1:1033058559470:web:104a1e03b59c481bcd1aff',
    messagingSenderId: '1033058559470',
    projectId: 'consiergego',
    authDomain: 'consiergego.firebaseapp.com',
    storageBucket: 'consiergego.firebasestorage.app',
    measurementId: 'G-4PNS8VVJZW',
  );
}
